-- DROP TABLE MACHINE_HISTORY
-- DROP TABLE LAB_HISTORY 
-- DROP TABLE MACHINE_STORAGE 
-- DROP TABLE OS_LABS 
-- DROP TABLE LAB_SOFTWARES
-- DROP TABLE LAB
-- DROP TABLE MACHINE 
-- DROP TABLE OS 
-- DROP TABLE LOCATION 
-- DROP TABLE LOCATION_HISTORY 
-- DROP TABLE STORAGE 
-- DROP TABLE SOFTWARE

CREATE DATABASE LABS_DASHBOARD
GO
USE LABS_DASHBOARD
GO

CREATE TABLE [LOCATION] (
  [ID_LOCATION] int PRIMARY KEY IDENTITY(1, 1),
  [SET_BUILDING] int,
  [BUILDING] int,
  [ROOM] VARCHAR(10)
)
GO

CREATE TABLE [LOCATION_HISTORY](
  [ID_LOCATION_HISTORY] int PRIMARY KEY IDENTITY(1, 1),
  [FK_ID_LOCATION] INT NOT NULL,
  [SET_BUILDING] int,
  [BUILDING] int,
  [ROOM] VARCHAR(10),
  [LOG_DATE] DATETIME,
)

CREATE TABLE [LAB] (
  [ID_LAB] int PRIMARY KEY IDENTITY(1, 1),
  [FK_ID_LOCATION] INT NOT NULL,
  [FK_ID_MACHINE] INT NOT NULL,
  [NAME] VARCHAR(10),
  [LAST_UPDATE] date,
  [MODEL_MACHINE] VARCHAR(30),
  [PURCHASE_DATE] date,
  [NUMBER_MACHINES] int,
  [IP_ADDRESS] VARCHAR(16),
  [SUBNET_MASK] VARCHAR(16),
  [GATEWAY] VARCHAR(16),
)
GO

CREATE TABLE [LAB_HISTORY] (
  [ID_LAB_HISTORY] INT PRIMARY KEY IDENTITY(1, 1),
  [FK_ID_LAB] INT NOT NULL,
  [FK_ID_MACHINE] INT NOT NULL,
  
  [NAME] VARCHAR(10),
  [LAST_UPDATE] DATE,
  [MODEL_MACHINE] VARCHAR(30),
  [PURCHASE_DATE] DATE,
  [NUMBER_MACHINES] INT,

  [IP_ADDRESS] VARCHAR(16),
  [SUBNET_MASK] VARCHAR(16),
  [GATEWAY] VARCHAR(16),
  [LOG_DATE] DATETIME,
)
GO

CREATE TABLE [SOFTWARE] (
  [ID_SOFTWARE] int PRIMARY KEY IDENTITY(1, 1),
  [NAME] VARCHAR(40) NOT NULL,
  [VERSION] VARCHAR(10),
  [INSTRUCTION_INSTALL] VARCHAR(100)
)
GO

CREATE TABLE [OS] (
  [ID_OS] int PRIMARY KEY IDENTITY(1, 1),
  [OS_NAME] VARCHAR(20),
  [INSTALATION_INFO] VARCHAR(100)
)
GO

CREATE TABLE [MACHINE] (
  [ID_MACHINE] int PRIMARY KEY IDENTITY(1, 1),
  [MACHINE_NAME] VARCHAR(15),
  [SERIAL] VARCHAR(15),
  [HAS_MICROPHONE] bit,
  [HAS_WEBCAM] bit,
  [CPU_MODEL] VARCHAR(30),
  [MEMORY_SIZE] VARCHAR(4)
)
GO

CREATE TABLE [MACHINE_HISTORY] (
  [ID_MACHINE_HISTORY] int PRIMARY KEY IDENTITY(1, 1),
  [FK_ID_MACHINE] INT NOT NULL,
  [MACHINE_NAME] VARCHAR(15),
  [SERIAL] VARCHAR(15),
  [HAS_MICROPHONE] bit,
  [HAS_WEBCAM] bit,
  [CPU_MODEL] VARCHAR(30),
  [MEMORY_SIZE] VARCHAR(4),
  [ID_STORAGE] int,
  [LOG_DATE] datetime,
)
GO

CREATE TABLE [LAB_SOFTWARES] (
  [FK_ID_LAB] int NOT NULL,
  [FK_ID_SOFTWARE] int NOT NULL
)
GO

CREATE TABLE [OS_LABS] (
  [FK_ID_LAB] int NOT NULL,
  [FK_ID_OS] int NOT NULL
)
GO

CREATE TABLE [MACHINE_STORAGE] (
  [FK_ID_STORAGE] int NOT NULL,
  [FK_ID_MACHINE] INT NOT NULL
)
GO

CREATE TABLE [STORAGE] (
  [ID_STORAGE] INT PRIMARY KEY IDENTITY(1, 1),
  [STORAGE_SIZE] VARCHAR(10),
  [DISK_TYPE] VARCHAR(10)
)
GO

ALTER TABLE [LAB_SOFTWARES] ADD FOREIGN KEY ([FK_ID_SOFTWARE]) REFERENCES [SOFTWARE] ([ID_SOFTWARE])
GO

ALTER TABLE [OS_LABS] ADD FOREIGN KEY ([FK_ID_OS]) REFERENCES [OS] ([ID_OS])
GO

ALTER TABLE [OS_LABS] ADD FOREIGN KEY ([FK_ID_LAB]) REFERENCES [LAB] ([ID_LAB])
GO

ALTER TABLE [LAB] ADD FOREIGN KEY ([FK_ID_LOCATION]) REFERENCES [LOCATION] ([ID_LOCATION])
GO

ALTER TABLE [LAB_SOFTWARES] ADD FOREIGN KEY ([FK_ID_LAB]) REFERENCES [LAB] ([ID_LAB])
GO

ALTER TABLE [LAB] ADD FOREIGN KEY ([FK_ID_MACHINE]) REFERENCES [MACHINE] ([ID_MACHINE])
GO

ALTER TABLE [MACHINE_HISTORY] ADD FOREIGN KEY ([FK_ID_MACHINE]) REFERENCES [MACHINE] ([ID_MACHINE])
GO

ALTER TABLE [MACHINE_STORAGE] ADD FOREIGN KEY ([FK_ID_MACHINE]) REFERENCES [MACHINE] ([ID_MACHINE])
GO

ALTER TABLE [MACHINE_STORAGE] ADD FOREIGN KEY ([FK_ID_STORAGE]) REFERENCES [STORAGE] ([ID_STORAGE])
GO

ALTER TABLE [LAB_HISTORY] ADD FOREIGN KEY ([FK_ID_LAB]) REFERENCES [LAB] ([ID_LAB])
GO

ALTER TABLE [LOCATION_HISTORY] ADD FOREIGN KEY ([FK_ID_LOCATION]) REFERENCES [LOCATION] ([ID_LOCATION])
GO


INSERT INTO SOFTWARE (NAME,VERSION,INSTRUCTION_INSTALL) VALUES
	 (N'Microsoft Office',N'2019',N''),
	 (N'Adobe Premiere ',N'2020',N''),
	 (N'Adobe Photoshop',N'2020',N''),
	 (N'Solidworks',N'2019',N''),
	 (N'NetBeans',N'8.2',N''),
	 (N'Arduino IDE',N'1.8.13',N''),
	 (N'Corel draw',N'2017',N''),
	 (N'Adobe Ilustrator',N'2021',N'Licença do software está disponível no servidor de arquivos');
	  
	 INSERT INTO OS (OS_NAME,INSTALATION_INFO) VALUES
	 (N'Windows 10 Education',NULL),
	 (N'Linux Ubuntu 12.04',NULL),
	 (N'Linux Ubuntu 18.04',NULL),
	 (N'Windows 7 Enterprise',NULL);